### ISSUE TITLE
Not compatible with 1.20.5

### ISSUE THREAD

**Issue by krafg** [JackFred2/MoreChatHistory#11]
On modrinth page says that it is compatible, but I got a crash:

---- Minecraft Crash Report ----
// I blame Dinnerbone.

Time: 2024-04-23 17:52:51
Description: Initializing game

java.lang.RuntimeException: Mixin transformation of net.minecraft.class_338 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	at net.minecraft.class_315.<init>(class_315.java:509)
	at net.minecraft.class_310.<init>(class_310.java:486)
	at net.minecraft.client.main.Main.main(Main.java:223)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
	... 10 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [morechathistory.mixins.json:ChatComponentMixin from mod morechathistory] from phase [DEFAULT] in config [morechathistory.mixins.json] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:589)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379)
	... 13 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Critical injection failure: @ModifyConstant annotation on morechathistory_changeMaxHistory could not find any targets matching 'Lnet/minecraft/class_338;method_1815(Lnet/minecraft/class_2561;Lnet/minecraft/class_7469;ILnet/minecraft/class_7591;Z)V' in net.minecraft.class_338. Using refmap client-morechathistory-refmap.json [PREINJECT Applicator Phase -> morechathistory.mixins.json:ChatComponentMixin from mod morechathistory -> Prepare Injections ->  -> constant$bfe000$morechathistory$changeMaxHistory(I)I -> Parse]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.validateTargets(InjectionInfo.java:658)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.findTargets(InjectionInfo.java:589)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.readAnnotation(InjectionInfo.java:330)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:316)
	at org.spongepowered.asm.mixin.injection.struct.ModifyConstantInjectionInfo.<init>(ModifyConstantInjectionInfo.java:54)
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo$InjectorEntry.create(InjectionInfo.java:149)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.parse(InjectionInfo.java:710)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1329)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1053)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:422)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	... 13 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	at net.minecraft.class_315.<init>(class_315.java:509)
	at net.minecraft.class_310.<init>(class_310.java:486)

-- Initialization --
Details:
	Modules: 
		ADVAPI32.dll:API base de Windows 32 avanzado:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		COMCTL32.dll:Biblioteca de controles de la experiencia del usuario:6.10 (WinBuild.160101.0800):Microsoft Corporation
		CRYPT32.dll:Crypto API32:10.0.22621.2860 (WinBuild.160101.0800):Microsoft Corporation
		CRYPTBASE.dll:Base cryptographic API DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		CRYPTSP.dll:Cryptographic Service Provider API:10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation
		DBGHELP.DLL:Windows Image Helper:10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation
		DNSAPI.dll:DLL de API de cliente DNS:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		GDI32.dll:GDI Client DLL:10.0.22621.3085 (WinBuild.160101.0800):Microsoft Corporation
		IMM32.DLL:Multi-User Windows IMM32 API Client DLL:10.0.22621.3374 (WinBuild.160101.0800):Microsoft Corporation
		IPHLPAPI.DLL:API auxiliar para IP:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		KERNEL32.DLL:Archivo DLL de cliente API BASE de Windows NT:10.0.22621.3374 (WinBuild.160101.0800):Microsoft Corporation
		KERNELBASE.dll:Archivo DLL de cliente API BASE de Windows NT:10.0.22621.3374 (WinBuild.160101.0800):Microsoft Corporation
		MpOav.dll:IOfficeAntiVirus Module:4.18.24030.9 (cd8105518e5571788ee3b6a178bae8fbcdf461a8):Microsoft Corporation
		NSI.dll:NSI User-mode interface DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		NTASN1.dll:Microsoft ASN.1 API:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		OLEAUT32.dll:OLEAUT32.DLL:10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation
		Ole32.dll:Microsoft OLE para Windows:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		POWRPROF.dll:Archivo DLL auxiliar del perfil de energía:10.0.22621.3374 (WinBuild.160101.0800):Microsoft Corporation
		PSAPI.DLL:Process Status Helper:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		Pdh.dll:Ayudante de los datos de rendimiento DLL de Windows:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		RPCRT4.dll:Tiempo de ejecución de llamada a procedimiento remoto:10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation
		SHCORE.dll:SHCORE:10.0.22621.2860 (WinBuild.160101.0800):Microsoft Corporation
		SHELL32.dll:Archivo DLL común del shell de Windows:10.0.22621.2860 (WinBuild.160101.0800):Microsoft Corporation
		UMPDC.dll:User Mode Power Dependency Coordinator:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		USER32.dll:Archivo DLL de cliente API USER de Windows multiusuario:10.0.22621.2860 (WinBuild.160101.0800):Microsoft Corporation
		USERENV.dll:Userenv:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		VCRUNTIME140.dll:Microsoft® C Runtime Library:14.29.30139.0 built by: vcwrkspc:Microsoft Corporation
		VERSION.dll:Version Checking and File Installation Libraries:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		WINHTTP.dll:Servicios HTTP de Windows:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		WINMM.dll:MCI API DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		WS2_32.dll:DLL de 32 bits de Windows Socket 2.0:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		amsi.dll:Anti-Malware Scan Interface:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		bcrypt.dll:Biblioteca de primitivas criptográficas de Windows:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		bcryptPrimitives.dll:Windows Cryptographic Primitives Library:10.0.22621.3374 (WinBuild.160101.0800):Microsoft Corporation
		clbcatq.dll:COM+ Configuration Catalog:2001.12.10941.16384 (WinBuild.160101.0800):Microsoft Corporation
		combase.dll:Microsoft COM para Windows:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		dbgcore.DLL:Windows Core Debugging Helpers:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		extnet.dll:OpenJDK Platform binary:21.0.3.0:Microsoft
		fwpuclnt.dll:API de modo usuario de FWP/IPsec:10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation
		gdi32full.dll:GDI Client DLL:10.0.22621.3374 (WinBuild.160101.0800):Microsoft Corporation
		glfw.dll:GLFW 3.4.0 DLL:3.4.0:GLFW
		java.dll:OpenJDK Platform binary:21.0.3.0:Microsoft
		javaw.exe:OpenJDK Platform binary:21.0.3.0:Microsoft
		jemalloc.dll
		jimage.dll:OpenJDK Platform binary:21.0.3.0:Microsoft
		jli.dll:OpenJDK Platform binary:21.0.3.0:Microsoft
		jna15300471099196307712.dll:JNA native library:7.0.0:Java(TM) Native Access (JNA)
		jsvml.dll:OpenJDK Platform binary:21.0.3.0:Microsoft
		jvm.dll:OpenJDK 64-Bit server VM:21.0.3.0:Microsoft
		kernel.appcore.dll:AppModel API Host:10.0.22621.2715 (WinBuild.160101.0800):Microsoft Corporation
		lwjgl.dll
		management.dll:OpenJDK Platform binary:21.0.3.0:Microsoft
		management_ext.dll:OpenJDK Platform binary:21.0.3.0:Microsoft
		msvcp140.dll:Microsoft® C Runtime Library:14.29.30139.0 built by: vcwrkspc:Microsoft Corporation
		msvcp_win.dll:Microsoft® C Runtime Library:10.0.22621.3374 (WinBuild.160101.0800):Microsoft Corporation
		msvcrt.dll:Windows NT CRT DLL:7.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation
		mswsock.dll:Proveedor de servicios de Microsoft Windows Sockets 2.0:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		napinsp.dll:Proveedor de correcciones de compatibilidad (shim) de nomenclaturas de correo electrónico:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		ncrypt.dll:Enrutador de Windows NCrypt:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		net.dll:OpenJDK Platform binary:21.0.3.0:Microsoft
		nio.dll:OpenJDK Platform binary:21.0.3.0:Microsoft
		nlansp_c.dll:NLA Namespace Service Provider DLL:10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation
		ntdll.dll:DLL del nivel de Windows NT:10.0.22621.3374 (WinBuild.160101.0800):Microsoft Corporation
		perfos.dll:DLL de objetos de rendimiento del sistema Windows:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		pfclient.dll:SysMain Client:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		pnrpnsp.dll:Proveedor de espacio de nombres PNRP:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		profapi.dll:User Profile Basic API:10.0.22621.3374 (WinBuild.160101.0800):Microsoft Corporation
		rasadhlp.dll:Remote Access AutoDial Helper:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		rsaenh.dll:Microsoft Enhanced Cryptographic Provider:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		sechost.dll:Host for SCM/SDDL/LSA Lookup APIs:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		shlwapi.dll:Biblioteca de utilidades de Shell:10.0.22621.2860 (WinBuild.160101.0800):Microsoft Corporation
		sunmscapi.dll:OpenJDK Platform binary:21.0.3.0:Microsoft
		ucrtbase.dll:Microsoft® C Runtime Library:10.0.22621.3374 (WinBuild.160101.0800):Microsoft Corporation
		vcruntime140_1.dll:Microsoft® C Runtime Library:14.29.30139.0 built by: vcwrkspc:Microsoft Corporation
		verify.dll:OpenJDK Platform binary:21.0.3.0:Microsoft
		win32u.dll:Win32u:10.0.22621.3447 (WinBuild.160101.0800):Microsoft Corporation
		windows.storage.dll:API de almacenamiento de Microsoft WinRT:10.0.22621.2860 (WinBuild.160101.0800):Microsoft Corporation
		winrnr.dll:LDAP RnR Provider DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		wintypes.dll:DLL de tipos basados en Windows:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		wshbth.dll:Windows Sockets Helper DLL:10.0.22621.3374 (WinBuild.160101.0800):Microsoft Corporation
		wshunix.dll:AF_UNIX Winsock2 Helper DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		zip.dll:OpenJDK Platform binary:21.0.3.0:Microsoft
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:223)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- System Details --
Details:
	Minecraft Version: 1.20.5
	Minecraft Version ID: 1.20.5
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 21.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 178418160 bytes (170 MiB) / 503316480 bytes (480 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 16
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 7 3700X 8-Core Processor             
	Identifier: AuthenticAMD Family 23 Model 113 Stepping 0
	Microarchitecture: Zen 2
	Frequency (GHz): 3.60
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: AMD Radeon RX 6700 XT
	Graphics card #0 vendor: Advanced Micro Devices, Inc.
	Graphics card #0 VRAM (MB): 12272.00
	Graphics card #0 deviceId: VideoController1
	Graphics card #0 versionInfo: 31.0.24027.1012
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 3.60
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 3.60
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 38814.99
	Virtual memory used (MB): 14791.95
	Swap memory total (MB): 22528.00
	Swap memory used (MB): 96.90
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		betterpingdisplay: Better Ping Display 1.1.1
		cloth-config: Cloth Config v13 13.0.121
			cloth-basic-math: cloth-basic-math 0.6.1
		continuity: Continuity 3.0.0-beta.4+1.20.2
		dark-loading-screen: Dark Loading Screen 1.6.14
		fabric-api: Fabric API 0.97.6+1.20.5
			fabric-api-base: Fabric API Base 0.4.40+80f8cf510d
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.59+e9d2a72b0d
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.24+76551cf60d
			fabric-block-api-v1: Fabric Block API (v1) 1.0.20+6dfe4c9b0d
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.8+80f8cf510d
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.50+80f8cf510d
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.12+7f945d5b0d
			fabric-command-api-v1: Fabric Command API (v1) 1.2.45+f71b366f0d
			fabric-command-api-v2: Fabric Command API (v2) 2.2.24+80f8cf510d
			fabric-commands-v0: Fabric Commands (v0) 0.2.62+df3654b30d
			fabric-content-registries-v0: Fabric Content Registries (v0) 8.0.4+b82b23920d
			fabric-convention-tags-v1: Fabric Convention Tags 2.0.3+7f945d5b0d
			fabric-convention-tags-v2: Fabric Convention Tags (v2) 2.0.0+2b43c5c80d
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.27+80f8cf510d
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.1.15+2a2c66b60d
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 19.0.5+7f945d5b0d
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.68+947939130d
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.6.8+e9d2a72b0d
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.7.6+c5fc38b30d
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.50+80f8cf510d
			fabric-item-api-v1: Fabric Item API (v1) 8.1.1+17e985d60d
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.38+aae0949a0d
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.45+80f8cf510d
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.43+df3654b30d
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.3.4+c5fc38b30d
			fabric-loot-api-v2: Fabric Loot API (v2) 3.0.4+97f703da0d
			fabric-message-api-v1: Fabric Message API (v1) 6.0.10+109a837c0d
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.12+80f8cf510d
			fabric-models-v0: Fabric Models (v0) 0.4.11+9386d8a70d
			fabric-networking-api-v1: Fabric Networking API (v1) 4.0.7+9342ba640d
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 15.1.3+c5fc38b30d
			fabric-particles-v1: Fabric Particles (v1) 4.0.0+c5fc38b30d
			fabric-recipe-api-v1: Fabric Recipe API (v1) 5.0.2+c5fc38b30d
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 5.0.14+f1240ba70d
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.2.12+97f703da0d
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.5.12+80f8cf510d
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.61+df3654b30d
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.46+73761d2e0d
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.1.3+2c869ded0d
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.64+df3654b30d
			fabric-rendering-v1: Fabric Rendering (v1) 4.2.4+b21c00cb0d
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 4.0.1+74e2f5600d
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 1.0.5+c5f2432c0d
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.21+7b70ea8a0d
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.71+b21c00cb0d
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.21+c5fc38b30d
			fabric-transfer-api-v1: Fabric Transfer API (v1) 5.1.6+c5fc38b30d
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 6.0.10+74e2f5600d
		fabricloader: Fabric Loader 0.15.10
			mixinextras: MixinExtras 0.3.5
		iris: Iris 1.7.0+mc1.20.5
			io_github_douira_glsl-transformer: glsl-transformer 2.0.0-pre13
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.11.1
		jade: Jade 14.0.1+fabric
		java: OpenJDK 64-Bit Server VM 21
		logical_zoom: Logical Zoom 0.0.22
		minecraft: Minecraft 1.20.5
		modmenu: Mod Menu 10.0.0-beta.1
		morechathistory: More Chat History 1.3.0
		sodium: Sodium 0.5.8+mc1.20.5
		sound_physics_remastered: Sound Physics Remastered 1.20.4-1.3.1
		tectonic: Tectonic 2.3.4
	Launched Version: fabric-loader-0.15.10-1.20.5
	Launcher name: minecraft-launcher
	Backend library: LWJGL version 3.3.3-snapshot
	Backend API: Unknown
	Window size: <not initialized>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Universe: 404
	Type: Client (map_client.txt)
	Locale: es_CL
	CPU: <unknown>

**Comment by JackFred2** [comment]
Thought I tested this in the pre releases; guess not. Simple fix in ~5 min

**Comment by JackFred2** [comment]
290c8849d33d6e8a989e26715a192d1472f983de

**Comment by krafg** [comment]
Yep, working flawlessly. Thanks.

https://i.imgur.com/00AC0JJ.png
